# Generated by Django 4.2.2 on 2024-03-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmanageruser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="taskmanageruser",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
