# Generated by Django 4.2.2 on 2024-03-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_taskmanageruser_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="taskmanageruser", name="groups",),
        migrations.RemoveField(model_name="taskmanageruser", name="organization",),
        migrations.RemoveField(model_name="taskmanageruser", name="user_permissions",),
        migrations.DeleteModel(name="Organization",),
        migrations.DeleteModel(name="TaskManagerUser",),
    ]
