# Generated by Django 4.2.2 on 2024-03-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="task", options={},),
    ]
